name: rsapp_peat
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=2.3
  - pandas=3.0
  - xarray=2025.12
  - geopandas=1.1
  - rasterio=1.4
  - rioxarray=0.18
  - cartopy=0.25
  - netcdf4=1.7
  - seaborn=0.13
  - matplotlib=3.10
  - rasterstats=0.20
  - ipykernel